### ISSUE TITLE
Q: How to use 'make' command and 'make competition' command? 

### ISSUE THREAD

**Issue by YSIT21013** [2021-SIT-AdvancedAlgorithms/PA2_Closest_Pair#1]
![image](https://user-images.githubusercontent.com/91630452/137140419-81ac790f-7ea6-4745-b1d2-2acc19e3ee09.png)
Whenever I try to use the command that you said, the error occurs.
In addition, In 'Makefile', 'make competition' command is `echo '99999' | ./closest_pair n 2d` and it seems like it doesn't match what was written in the google document since n is naive, not divide and conquer. Please check it carefully. Thanks.

**Comment by sungminlee114** [comment]
1. `make` command can be used by installing make (sudo apt-get install make)
2. You are right. Thanks for the contribution. Extra credits!
